name: Create AWS ECR
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      envName:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev
        - prod
        - all
jobs:
  create-ecr:
    runs-on: ubuntu-latest

    env:
      PRODUCT: ${{ github.event.inputs.productName }}
      SERVICE: ${{ github.event.inputs.serviceName }}
      ENVNAME: ${{ github.event.inputs.envName }}

    steps:
    - name: Echo test
      run: |
        echo "Product: ${{ github.event.inputs.productName }}"
        echo "Repo: ${{ github.event.inputs.serviceName }}"
        echo "Product: $PRODUCT"
        echo "Service: $SERVICE"
        echo "Env: $ENVNAME"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create changes
      run: |
        date  >> report.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: ${{ env.ENVNAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}
        delete-branch: true
        title: "Add ECR ${{ env.ENVNAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}"
        commit-message: "[Add ecr ${{ env.ENVNAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}] automated change"
        body: |
            Update report
            - Add ecr ${{ env.ENVNAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}
            - Auto-generated by github action [${{ github.workflow }}]
        labels: |
          ECR
          AWS
          Automated PR
          ${{ env.ENVNAME }}
