name: Create AWS ECR
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        default: 'airslate'
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      envName:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev
        - prod
        - all
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Product: ${{ github.event.inputs.productName }}"
        echo "Repo: ${{ github.event.inputs.serviceName }}"
