name: Create AWS ECR
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      ENV_NAME:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev
        - prod
        - all
jobs:
  create-ecr:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      PRODUCT: ${{ github.event.inputs.productName }}
      SERVICE: ${{ github.event.inputs.serviceName }}
      ENV_NAME: ${{ github.event.inputs.ENV_NAME }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform templating
      env:
        REPO_PATH: "infra/${{ env.ENV_NAME }}/ecr/${{ env.PRODUCT }}/${{ env.SERVICE }}"
      run: |
        set -euo pipefail
        if [[ -d "${REPO_PATH}" ]]; then
          echo "${REPO_PATH} already exist!"
          exit 1
        else
          cp -rv template/ecr "${REPO_PATH}"
          
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: ${{ env.ENV_NAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}
        delete-branch: true
        title: "Add ECR ${{ env.ENV_NAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}"
        commit-message: "[Add ecr ${{ env.ENV_NAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}] automated change"
        body: |
            Update report
            - Add ecr ${{ env.ENV_NAME }}/${{ env.PRODUCT }}/${{ env.SERVICE }}
            - Auto-generated by github action [${{ github.workflow }}]
        labels: |
          ECR
          AWS
          Automated PR
          ${{ env.ENV_NAME }}
