name: Create ECR Pull Request
on:
  workflow_dispatch:
jobs:
  create-ecr-pr:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      INFRA_REPO: "EugeneAikashev/aws-ecr-infra"

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ env.INFRA_REPO }}

    - name: Templating
      run: |
        date >> date_check.txt

    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.EUGENEAPP_APP_ID }}
        private_key: ${{ secrets.EUGENEAPP_APP_PRIVATE_KEY }}
        repository: ${{ env.INFRA_REPO }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate-token.outputs.token }}
        # token: ${{ secrets.API_TOKEN_GITHUB }}
