name: Create ECR Pull Request
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      envName:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev+prod
        - dev
        - prod
jobs:
  create-ecr-pr:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      REPO_NAME: "EugeneAikashev/aws-ecr-infra"
      PRODUCT: ${{ github.event.inputs.productName }}
      SERVICE: ${{ github.event.inputs.serviceName }}
      ENV_NAME: ${{ github.event.inputs.envName }}
      REPO_PATH: "infra/${{ github.event.inputs.envName }}/ecr/${{ github.event.inputs.productName }}/${{ github.event.inputs.serviceName }}"

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_NAME }}

    - name: Templating
      run: |
        set -euo pipefail

        if [[ "${SERVICE}" =~ [^a-z0-9\-] ]]; then
          echo "Service name is invalid. Only lowercase alphanum and dash are allowed!"
          exit 1
        fi

        if [[ -d "${REPO_PATH}" ]]; then
          echo "${REPO_PATH} is already exist!"
          exit 1
        fi

        mkdir -p "${REPO_PATH}"
        cp -rTv template/ecr/ "${REPO_PATH}"
        sed -i "s/PLACEHOLDER_PRODUCT/${PRODUCT}/g" "${REPO_PATH}/settings.tfvars"
        sed -i "s/PLACEHOLDER_SERVICE/${SERVICE}/g" "${REPO_PATH}/settings.tfvars"
        grep ecr_repo_name "${REPO_PATH}/settings.tfvars"

    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.EUGENEAPP_APP_ID }}
        private_key: ${{ secrets.EUGENEAPP_APP_PRIVATE_KEY }}
        #repository: ${{ env.REPO_NAME }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate-token.outputs.token }}
        # token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: ${{ env.REPO_PATH }}
        delete-branch: true
        title: "Add ${{ env.REPO_PATH }}"
        commit-message: "[Add ${{ env.REPO_PATH }}] automated change"
        assignees: ${{ github.actor }}
        body: |
            Update report
            - Add ${{ env.REPO_PATH }}
            - Auto-generated by github action [${{ github.workflow }}]
        labels: |
          ECR
          AWS
          Automated PR
          ${{ env.ENV_NAME }}
