name: Create AWS ECR
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        default: 'airslate'
        options:
        - airslate
        - pdffiller
        - signnow
      repoName:
        description: 'Repo name'
        required: true
        default: 'blabla'
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Product: ${{ github.event.inputs.productName }}"
        echo "Repo: ${{ github.event.inputs.repoName }}"
