name: Create AWS ECR
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      envName:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev
        - prod
        - all
jobs:
  create-repo:
    runs-on: ubuntu-latest

    env:
      PRODUCT: ${{ github.event.inputs.productName }}
      SERVICE: ${{ github.event.inputs.serviceName }}
      ENVNAME: ${{ github.event.inputs.envName }}"

    steps:
    - name: Echo test
      run: |
        echo "Product: ${{ github.event.inputs.productName }}"
        echo "Repo: ${{ github.event.inputs.serviceName }}"
        echo "Product: $PRODUCT"
        echo "Service: $SERVICE"
        echo "Env: $ENVNAME"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create changes
      run: |
        date  >> report.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
