name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.EUGENEAPP_APP_ID }}
        private_key: ${{ secrets.EUGENEAPP_APP_PRIVATE_KEY }}

    - name: Use token
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
        VAR1: "variable 1"
      run: |
        echo "The generated token is masked: ${TOKEN}"
        echo "${VAR1}"

    - name: step2
      run: echo "${VAR1}"


    # - name: Checkout Infra
    #   uses: actions/checkout@v3
    #   with:
    #     repository: EugeneAikashev/aws-ecr-infra

    # - run: |
    #     pwd
    #     tree
    #     cat README.md
    #     date >> report.txt

    # - name: Create PR to Infra
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     token: ${{ secrets.API_TOKEN_GITHUB }}
