name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-name

    defaults:
      run:
        shell: bash


    steps:

    - run: |
        echo ${{ github.actor }}
