name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: EugeneAikashev/aws-ecr-infra

    - run: |
        pwd
        tree
        cat README.md
        date >> report.txt
