name: Trigger remote action
on:
  workflow_dispatch:
    inputs:
      productName:
        type: choice
        description: 'Product Name'
        required: true
        options:
        - airslate
        - pdffiller
        - signnow
      serviceName:
        description: 'Service name'
        required: true
      envName:
        type: choice
        description: 'Environment'
        required: true
        options:
        - dev
        - prod
        - dev+prod
jobs:
  create-ecr:
    runs-on: ubuntu-latest

    steps:

    - name: Lint
      env:
        SERVICE: ${{ github.event.inputs.serviceName }}
      run: |
        if [[ "${SERVICE}" =~ [^a-z0-9\-] ]]; then
          echo "Service name is invalid. Only lowercase alphanum and dash are allowed!"
          exit 1
        fi

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        repository: EugeneAikashev/aws-ecr-infra
        event-type: create-aws-ecr
        client-payload: '{"productName": "${{ github.event.inputs.productName }}", "serviceName": "${{ github.event.inputs.serviceName }}" , "envName": "${{ github.event.inputs.envName }}"}'
